L = 50;
r = 47;
d = 20;
n = 24;
cnt = 0;
idx = [14 20 4 16 24 8 12 22 6 18 2 10 13 21 5 17 1 9];
names = {
    'lab_teal_1', ...
    'lab_violet_1', ...
    'lab_orange_1', ...
    'lab_blue_1', ...
    'lab_pink_1', ...
    'lab_green_1', ...
    'lab_teal_2', ...
    'lab_violet_2', ...
    'lab_orange_2', ...
    'lab_blue_2', ...
    'lab_pink_2', ...
    'lab_green_2', ...
    'lab_teal_3', ...
    'lab_violet_3', ...
    'lab_orange_3', ...
    'lab_blue_3', ...
    'lab_pink_3', ...
    'lab_green_3', ...
    }
color = {};
close all
fig = figure();
ax = axes(fig, 'NextPlot', 'add');
for i = 0:2*pi/n:2*pi-0.01
    cnt = cnt + 1;
    if mod(cnt, 4) == 3
        continue
    end
    a = cos(i) .* (r - d .* mod(cnt, 2));
    b = sin(i) .* (r - d .* mod(cnt, 2));
    color{cnt} = lab2rgb([L - (d/2) .* mod(cnt, 2), a, b], 'ColorSpace', 'adobe-rgb-1998', 'WhitePoint','icc'); %#ok<SAGROW>
    if any(color{cnt} < 0) || any(color{cnt} > 1)
        continue
    end
    plot(ax, a, b, '.', 'Color', color{cnt}, 'MarkerSize', 150)
    text(ax, a, b, sprintf('%i', cnt))
end
axis square


fig = figure();
ax = axes(fig, 'NextPlot', 'add');

color = color(idx);
color = cat(1, color{:});
for i = 1:length(names)
    plot(1, i, '.', 'Color', color(i, :), 'MarkerSize', 150)
    text(1.2, i, sprintf('%s', names{i}))
    fprintf('C.%s = [%.8f, %.8f, %.8f];\n', names{i}, color(i, 1), color(i, 2), color(i, 3))
end
