% REGISTERUSER
% Asks the user to register.

% Authors:
%   Rick Wassing, Woolcock Institute of Medical Research, Sydney, Australia
%
% History:
%   Created 2023-08-22, Rick Wassing

% Cicada (C) 2023 by Rick Wassing is licensed under
% Attribution-NonCommercial-ShareAlike 4.0 International
% This license requires that reusers give credit to the creator. It allows
% reusers to distribute, remix, adapt, and build upon the material in any
% medium or format, for noncommercial purposes only. If others modify or
% adapt the material, they must license the modified material under
% identical terms.

classdef RegisterUser < matlab.ui.componentcontainer.ComponentContainer
    % *********************************************************************
    % PROPERTIES
    properties
        Size = [450, 394];
        Auth;
        Verbose;
    end
    properties (Access = public, Transient, NonCopyable)
        Panel matlab.ui.container.Panel
        GridLayout matlab.ui.container.GridLayout
        Text
        Labels
        Inputs
        Buttons
        WelcomeImage
        WelcomePanel
        FormPanel
        WelcomeGridLayout
        FormGridLayout
        TitleText = 'Thank you for using Cicada';
        LicenseText = 'Cicada Actigraphy Suite © 2023 by Rick Wassing is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.';
        DisclaimerText = 'The software is provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and non-infringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.'; 
        FormText = 'By providing this app open-source and free of charge, Cicada aims to enable science for all. It would benefit me if you could please register the use of this app. This information may be used in presentations, publications, grant applications, etc.';
    end
    % *********************************************************************
    % METHODS
    methods (Access = protected)
        % =================================================================
        function setup(Obj)
            % -------------------------------------------------------------
            % Create sub-components
            % -------------------------------------------------------------
            Colors = app_colors();
            % -------------------------------------------------------------
            Obj.Tag = 'RegisterUser';
            Obj.Panel = uipanel(Obj, ...
                'Title', '', ...
                'FontSize', 8, ...
                'FontWeight', 'bold', ...
                'Tag', 'Register_Panel', ...
                'ForegroundColor', Colors.body_primary, ...
                'BackgroundColor', Colors.bg_secondary, ...
                'HighLightColor', [0.8, 0.8, 0.8], ...
                'Units', 'normalized', ...
                'Position', [0, 0, 1, 1]);
            % -------------------------------------------------------------
            Obj.GridLayout = uigridlayout(Obj.Panel, ...
                'Tag', 'RegisterUser_GridLayout', ...
                'ColumnWidth', {'1x', '1x'}, ...
                'RowHeight', {'1x', 24}, ...
                'ColumnSpacing', 12, ...
                'RowSpacing', 6, ...
                'Padding', 12, ...
                'BackgroundColor', Colors.bg_secondary);
            % -------------------------------------------------------------
            Obj.WelcomePanel = uipanel(Obj.GridLayout, ...
                'FontSize', 8, ...
                'Tag', 'RegisterUser_WelcomePanel', ...
                'BorderType', 'none', ...
                'ForegroundColor', Colors.body_primary, ...
                'BackgroundColor', Colors.bg_secondary, ...
                'HighLightColor', [0.8, 0.8, 0.8]);
            Obj.WelcomePanel.Layout.Row = 1;
            Obj.WelcomePanel.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.WelcomeGridLayout = uigridlayout(Obj.WelcomePanel, ...
                'Tag', 'RegisterUser_WelcomeGridLayout', ...
                'ColumnWidth', {'1x'}, ...
                'RowHeight', {102, 24, 52, 138}, ...
                'ColumnSpacing', 0, ...
                'RowSpacing', 6, ...
                'Padding', 0, ...
                'BackgroundColor', Colors.bg_secondary);
            % -------------------------------------------------------------
            Obj.WelcomeImage = uiimage(Obj.WelcomeGridLayout, ...
                'ImageSource', 'register-thanks.png', ...
                'ScaleMethod', 'fit');
            Obj.WelcomeImage.Layout.Row = 1;
            Obj.WelcomeImage.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Text(1).Obj = uilabel(Obj.WelcomeGridLayout, ...
                'Text', Obj.TitleText, ...
                'WordWrap', 'on', ...
                'VerticalAlignment', 'top', ...
                'FontWeight', 'bold', ...
                'FontColor', Colors.body_primary, ...
                'FontSize', 14);
            Obj.Text(1).Obj.Layout.Row = 2;
            Obj.Text(1).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Text(2).Obj = uilabel(Obj.WelcomeGridLayout, ...
                'Text', Obj.LicenseText, ...
                'WordWrap', 'on', ...
                'VerticalAlignment', 'top', ...
                'FontColor', Colors.body_secondary, ...
                'FontSize', 10);
            Obj.Text(2).Obj.Layout.Row = 3;
            Obj.Text(2).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Text(3).Obj = uilabel(Obj.WelcomeGridLayout, ...
                'Text', Obj.DisclaimerText, ...
                'WordWrap', 'on', ...
                'VerticalAlignment', 'top', ...
                'FontColor', Colors.body_secondary, ...
                'FontSize', 10);
            Obj.Text(3).Obj.Layout.Row = 4;
            Obj.Text(3).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.FormPanel = uipanel(Obj.GridLayout, ...
                'FontSize', 8, ...
                'Tag', 'Register_FormPanel', ...
                'BorderType', 'none', ...
                'ForegroundColor', Colors.body_primary, ...
                'BackgroundColor', Colors.bg_secondary, ...
                'HighLightColor', [0.8, 0.8, 0.8]);
            Obj.FormPanel.Layout.Row = 1;
            Obj.FormPanel.Layout.Column = 2;
            % -------------------------------------------------------------
            Obj.FormGridLayout = uigridlayout(Obj.FormPanel, ...
                'Tag', 'RegisterUser_FormGridLayout', ...
                'ColumnWidth', {'1x'}, ...
                'RowHeight', {24, 120, 18, 24, 18, 24, 18, 24, 18, 18}, ...
                'ColumnSpacing', 0, ...
                'RowSpacing', 3, ...
                'Padding', 0, ...
                'BackgroundColor', Colors.bg_secondary);
            % -------------------------------------------------------------
            Obj.Text(4).Obj = uilabel(Obj.FormGridLayout, ...
                'Text', 'Please register', ...
                'WordWrap', 'on', ...
                'VerticalAlignment', 'top', ...
                'FontWeight', 'bold', ...
                'FontColor', Colors.body_primary, ...
                'FontSize', 14);
            Obj.Text(4).Obj.Layout.Row = 1;
            Obj.Text(4).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Text(5).Obj = uilabel(Obj.FormGridLayout, ...
                'Text', Obj.FormText, ...
                'WordWrap', 'on', ...
                'VerticalAlignment', 'top', ...
                'FontWeight', 'bold', ...
                'FontColor', Colors.body_secondary, ...
                'FontSize', 12);
            Obj.Text(5).Obj.Layout.Row = 2;
            Obj.Text(5).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Labels(1).Obj = uilabel(Obj.FormGridLayout, ...
                'Text', 'Name', ...
                'FontWeight', 'bold', ...
                'VerticalAlignment', 'bottom', ...
                'FontColor', Colors.body_primary, ...
                'FontSize', 12);
            Obj.Labels(1).Obj.Layout.Row = 3;
            Obj.Labels(1).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Inputs(1).Obj = uieditfield(Obj.FormGridLayout, 'text', ...
                'Tag', 'name', ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~, event) Obj.setregistration(event));
            Obj.Inputs(1).Obj.Layout.Row = 4;
            Obj.Inputs(1).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Labels(2).Obj = uilabel(Obj.FormGridLayout, ...
                'Text', 'Institute', ...
                'FontWeight', 'bold', ...
                'VerticalAlignment', 'bottom', ...
                'FontColor', Colors.body_primary, ...
                'FontSize', 12);
            Obj.Labels(2).Obj.Layout.Row = 5;
            Obj.Labels(2).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Inputs(2).Obj = uieditfield(Obj.FormGridLayout, 'text', ...
                'Tag', 'institute', ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~, event) Obj.setregistration(event));
            Obj.Inputs(2).Obj.Layout.Row = 6;
            Obj.Inputs(2).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Labels(3).Obj = uilabel(Obj.FormGridLayout, ...
                'Text', 'Email', ...
                'FontWeight', 'bold', ...
                'VerticalAlignment', 'bottom', ...
                'FontColor', Colors.body_primary, ...
                'FontSize', 12);
            Obj.Labels(3).Obj.Layout.Row = 7;
            Obj.Labels(3).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Inputs(3).Obj = uieditfield(Obj.FormGridLayout, 'text', ...
                'Tag', 'email', ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~, event) Obj.setregistration(event));
            Obj.Inputs(3).Obj.Layout.Row = 8;
            Obj.Inputs(3).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Inputs(4).Obj = uicheckbox(Obj.FormGridLayout, ...
                'Tag', 'subscribe', ...
                'Text', 'Subscribe to updates', ...
                'Value', true, ...
                'FontColor', Colors.body_secondary, ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~, event) Obj.setregistration(event));
            Obj.Inputs(4).Obj.Layout.Row = 9;
            Obj.Inputs(4).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Inputs(5).Obj = uicheckbox(Obj.FormGridLayout, ...
                'Tag', 'accept', ...
                'Text', 'I accept the license terms', ...
                'FontColor', Colors.body_secondary, ...
                'FontSize', 11, ...
                'ValueChangedFcn', @(~, event) Obj.setregistration(event));
            Obj.Inputs(5).Obj.Layout.Row = 10;
            Obj.Inputs(5).Obj.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Buttons.Cancel = uibutton(Obj.GridLayout, ...
                'Text', 'USE ANONYMOUSLY', ...
                'Enable', 'off', ...
                'Tag', 'anonymous', ...
                'FontSize', 11, ...
                'FontWeight', 'bold', ...
                'FontColor', 'w', ...
                'BackgroundColor', Colors.bs_secondary, ...
                'ButtonPushedFcn', @(source, event) Obj.submit(event));
            Obj.Buttons.Cancel.Layout.Row = 2;
            Obj.Buttons.Cancel.Layout.Column = 1;
            % -------------------------------------------------------------
            Obj.Buttons.Submit = uibutton(Obj.GridLayout, ...
                'Text', 'REGISTER', ...
                'Enable', 'off', ...
                'FontSize', 11, ...
                'FontWeight', 'bold', ...
                'FontColor', 'w', ...
                'BackgroundColor', Colors.bs_success, ...
                'ButtonPushedFcn', @(source, event) Obj.submit(event));
            Obj.Buttons.Submit.Layout.Row = 2;
            Obj.Buttons.Submit.Layout.Column = 2;
        end
        % =================================================================
        function update(Obj)
            try
                % ---------------------------------------------------------
                % Timer
                if Obj.Verbose; Time = now; end %#ok<TNOW1>
                Obj.Auth
                % ---------------------------------------------------------
                if isempty(Obj.Auth)
                    Obj.Auth = struct(...
                        'name', '', ...
                        'institute', '', ...
                        'email', '', ...
                        'subscribe', 'yes', ...
                        'accept', 'no', ...
                        'askagain', 'no', ...
                        'is_registered', false, ...
                        'datetime', '');
                end
                % - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                Obj.Inputs(1).Obj.Value = Obj.Auth.name;
                Obj.Inputs(2).Obj.Value = Obj.Auth.institute;
                Obj.Inputs(3).Obj.Value = Obj.Auth.email;
                Obj.Inputs(4).Obj.Value = ifelse(strcmpi(Obj.Auth.subscribe, 'yes'), true, false);
                Obj.Inputs(5).Obj.Value = ifelse(strcmpi(Obj.Auth.accept, 'yes'), true, false);
                % ---------------------------------------------------------
                if Obj.Verbose
                    fprintf('>> CIC: RegisterUser updated in %.1g s.\n', (now-Time)*24*60*60); %#ok<TNOW1>
                end
            catch ME
                printerrormessage(ME, 'The error occurred during ''update'' in RegisterUser.m')
            end
        end
    end
    % *********************************************************************
    methods (Access = public)
        % =================================================================
        % Cancel 
        function setregistration(Obj, event)
            % -------------------------------------------------------------
            % Convert bool to 'yes' or 'no'
            if islogical(event.Value)
                val = ifelse(event.Value, 'yes', 'no');
            else
                val = event.Value;
            end
            % Set value
            Obj.Auth.(event.Source.Tag) = val;
            % -------------------------------------------------------------
            % Check if the buttons can be enabled
            if strcmpi(Obj.Auth.accept, 'yes')
                Obj.Buttons.Cancel.Enable = 'on';
            else
                Obj.Buttons.Cancel.Enable = 'off';
            end
            if ...
                    strcmpi(Obj.Auth.accept, 'yes') && ...
                    ~isempty(Obj.Auth.name) && ...
                    ~isempty(Obj.Auth.institute) && ...
                    ~isempty(Obj.Auth.email)
                Obj.Buttons.Submit.Enable = 'on';
            else
                Obj.Buttons.Submit.Enable = 'off';
            end
        end
        % =================================================================
        % Create or update event
        function submit(Obj, event)
            % Disable the imput and buttons right away to prevent double clicks
            for i = 1:length(Obj.Inputs)
                Obj.Inputs(i).Obj.Enable = 'off';
            end
            Obj.Buttons.Submit.Enable = 'off';
            Obj.Buttons.Cancel.Enable = 'off';
            drawnow();
            % Get app handle so we have access to the MS Flow URL
            app = app_gethandle();
            % Set date-time
            dt = datetime('now', 'TimeZone', 'local');
            dt = sprintf('%s (%s)', char(dt, 'uuuu-MM-dd''T''HH:mm:ss'), dt.TimeZone);
            % Check if we should anonymize the user details
            if ~strcmpi(event.Source.Text, 'register')
                Obj.Auth.name = 'anonymous';
                Obj.Auth.institute = 'n/a';
                Obj.Auth.email = 'john@doe.com';
                Obj.Auth.subscribe = 'no';
            end
            % Construct payload
            try
                httpreq(app.URL.MSFlow, ...
                    'user', Obj.PayLoad.name, ...
                    'institute', Obj.PayLoad.institute, ...
                    'email', lower(Obj.PayLoad.email), ...
                    'subscribe', Obj.PayLoad.subscribe, ...
                    'datetime', dt);
            catch
                % API request failed for some reason, don't mind, keep going
            end
            % -------------------------------------------------------------
            % Store app settings that we have registered (no need to ask again)
            app.Props.Settings.Auth = struct();
            app.Props.Settings.Auth.name = Obj.Auth.name;
            app.Props.Settings.Auth.institute = Obj.Auth.institute;
            app.Props.Settings.Auth.email = lower(Obj.Auth.email);
            app.Props.Settings.Auth.subscribe = Obj.Auth.subscribe;
            app.Props.Settings.Auth.accept = Obj.Auth.accept;
            app.Props.Settings.Auth.askagain = true;
            app.Props.Settings.Auth.is_registered = true;
            app.Props.Settings.Auth.datetime = dt;
            % - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
            app_savesettings(app.Props.Settings);
            % -------------------------------------------------------------
            % Close modal
            app.hModal(event, '');
        end
        % =================================================================
        function hUpdate(Obj, app, ~) %#ok<INUSD>
            try
                % Obj.update();
            catch ME
                printerrormessage(ME, 'The error occurred during ''hUpdate'' in RegisterUser.m')
            end
        end
    end
end